[package]
name = "nextgen_weightfile"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netcdf = "0.9.3"
serde = {version = "1.0.203", features = ["serde_derive"]}
serde_json = "1.0.119"
