[package]
name = "nextgen_weightfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netcdf = "0.8.1"
serde = {version = "1.0.164", features = ["serde_derive"]}
serde_json = "1.0.99"
